### ISSUE TITLE
WARNING: you are trying to process UTF-8 input

### ISSUE THREAD

**Issue by 9mm** [tilo/smarter_csv#150]
I'm using the `Readline` method with `StringIO`.

I get this warning about UTF8 

    WARNING: you are trying to process UTF-8 input, but did not open the input with "b:utf-8" option. See README file "NOTES about File Encodings".

I have consulted that part of the Readme but I don't see how I would actually fix this because I'm not reading anything from a file? (It's coming from the `ftp.getbinaryfile()` method in `Net::FTP`

**Comment by 9mm** [comment]
My CSV does appear to contain a BOM. I thought maybe I can do this according to StringIO docs...

    StringIO.new(csv_raw, mode: 'r:bom|utf-8')

But this appears to still leave the BOM in the file

**Comment by nonnenmacher** [comment]
don't know for 'writing'  CSV
but solved similar situation for reading and parsing such CSV with `BOM` bytes
with

```
smarter_csv_options = {
        #:chunk_size => 1,
          ...
	 :file_encoding => 'bom|utf-8'
    }
```

as `options` hash given to 

```
    SmarterCSV.process(filepath, smarter_csv_options)
```

I don't know if giving `:file_encoding => 'bom|utf-8'` for reading and `` :file_encoding => 'utf-8'`` will remove the BOM bytes (as it should normally be a standard to deal with or without it for utf-8 anyway).

**Comment by tilo** [comment]
@9mm @nonnenmacher can you provide a small sample CSV file? 

When handling data, using `force_encoding` and/or `mapping invalid/undef codes to `''` can also help.
I'd need to see a file to look into this further

**Comment by nonnenmacher** [comment]
sorry I can't (was some PayPal payments file).

If I could help further (as it seems a nice touch to see so old issues being solved), nice of you !

**Comment by tilo** [comment]
@9mm @nonnenmacher this should be fixed with version `1.8.0`, which has a [general approach to get rid of BOMs](https://github.com/tilo/smarter_csv/blob/931980ff9690f9d83ed4299793845810b4367493/lib/smarter_csv.rb#L541)

**Comment by key88sf** [comment]
@tilo FWIW, I am still getting this error with 1.8.2, when using `force_utf8: true` option.
